package perros;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class InterazPerros extends javax.swing.JFrame {
        
        final int precioPeq=3000;
        final int precioMed=5000;
        final int precioGran=10000;
        
        int numPerros=0;
        int horas=0;
                
        int pequeños=0;
        int medianos=0;
        int grandes=0;
        int costo=0;

    /**
     * Creates new form InterazPerros
     */
    public InterazPerros() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AgregarPerros = new javax.swing.JButton();
        cantPerros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CantHoras = new javax.swing.JTextField();
        registrarPerro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cheems = new javax.swing.JLabel();
        JLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 68, 0));
        jLabel1.setText("Cheems pet");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 68, 0));
        jLabel2.setText("Los mejores paseos de tu amigo canino");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 68, 0));
        jLabel3.setText("¿cuantos perros desea que paseemos?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        AgregarPerros.setBackground(new java.awt.Color(159, 111, 16));
        AgregarPerros.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        AgregarPerros.setForeground(new java.awt.Color(41, 31, 10));
        AgregarPerros.setText("agregar perros");
        AgregarPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPerrosActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarPerros, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 150, 40));

        cantPerros.setBackground(new java.awt.Color(235, 222, 194));
        cantPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantPerrosActionPerformed(evt);
            }
        });
        getContentPane().add(cantPerros, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 60, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 68, 0));
        jLabel4.setText("¿cuantos horas desea que paseemos a   ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 68, 0));
        jLabel5.setText("su(s) amigo(s) canino(s)?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        CantHoras.setBackground(new java.awt.Color(235, 222, 194));
        getContentPane().add(CantHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 60, -1));

        registrarPerro.setBackground(new java.awt.Color(159, 111, 16));
        registrarPerro.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        registrarPerro.setForeground(new java.awt.Color(41, 31, 10));
        registrarPerro.setText("enviar");
        registrarPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPerroActionPerformed(evt);
            }
        });
        getContentPane().add(registrarPerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 160, 50));

        jLabel9.setForeground(new java.awt.Color(61, 43, 5));
        jLabel9.setText("uno por uno tus perros");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jLabel8.setForeground(new java.awt.Color(61, 43, 5));
        jLabel8.setText("presiona para agregar ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(61, 43, 5));
        jLabel7.setText("by Esteban Rivera");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\actividad interfaces\\interfazPerros\\imagenes\\cheems-pequeño.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 90, 90));

        Cheems.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\actividad interfaces\\interfazPerros\\imagenes\\light-orange-color-solid-background-1920x1080.png")); // NOI18N
        getContentPane().add(Cheems, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 520, 550));

        JLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\actividad interfaces\\interfazPerros\\imagenes\\pngtree-cute-cartoon-dog-wallpaper-picture-image_1348618.jpg")); // NOI18N
        JLabelFondo.setText("jLabel6");
        getContentPane().add(JLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 930, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPerrosActionPerformed
        
        numPerros=Integer.parseInt(cantPerros.getText());
        for (int i = 0; i < numPerros; i++) {
            int tipoPerro=Integer.parseInt(JOptionPane.showInputDialog("que tipo es tu perro:\n1.pequeño\n2.mediano\n3.grande "));
            if(tipoPerro==1){
                pequeños++;
            }else if(tipoPerro==2){
                medianos++;
            }else if (tipoPerro==3) {
                grandes++;
            }else{
                JOptionPane.showMessageDialog(null, "ERROR\nese tipo de perro no existe");
                i--;
            }
            JOptionPane.showMessageDialog(null,"tu perro ha sido agregado con exito");
        }
    }//GEN-LAST:event_AgregarPerrosActionPerformed

    private void cantPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantPerrosActionPerformed
        
        
    }//GEN-LAST:event_cantPerrosActionPerformed

    private void registrarPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPerroActionPerformed
        horas=Integer.parseInt(CantHoras.getText());
        cantPerros.setText("");
        CantHoras.setText("");
        costo=(grandes*horas*precioGran)+(medianos*horas*precioMed)+(pequeños*horas*precioPeq);
        if(numPerros>1){
            costo=(int)(costo-(costo*0.1));
        }
        JOptionPane.showMessageDialog(null,"cantidad de perros= "+numPerros+"\nhoras de paseo= "+horas+"\ncosto total por el paseo= "+costo);
    }//GEN-LAST:event_registrarPerroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterazPerros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterazPerros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterazPerros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterazPerros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterazPerros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarPerros;
    private javax.swing.JTextField CantHoras;
    private javax.swing.JLabel Cheems;
    private javax.swing.JLabel JLabelFondo;
    private javax.swing.JTextField cantPerros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton registrarPerro;
    // End of variables declaration//GEN-END:variables
}
